package com.lzy.jshow.mapper;

import com.lzy.jshow.entity.AppUser;
import com.lzy.jshow.entity.AppUserExample;
import java.util.List;

import com.lzy.jshow.entity.SysPermission;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface AppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    long countByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int deleteByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int insert(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int insertSelective(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    List<AppUser> selectByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    AppUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByExampleSelective(@Param("row") AppUser row, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByExample(@Param("row") AppUser row, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByPrimaryKeySelective(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByPrimaryKey(AppUser row);
    
    
    @Select("select sp.perm_code from sys_permission sp " +
            "left join sys_role_permission srp on sp.id = srp.perm_id " +
            "left join sys_role sr on srp.role_id = sr.id " +
            "left join sys_user_role sur on sr.id = sur.role_id " +
            "left join app_user au on sur.user_id = au.id " +
            "where au.id = #{id}")
    List<String> permissionList(Long id);
}