package com.lzy.jshow.mapper;

import com.lzy.jshow.entity.RolePermission;
import com.lzy.jshow.entity.RolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int insert(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int insertSelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int updateByExampleSelective(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int updateByExample(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int updateByPrimaryKeySelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    int updateByPrimaryKey(RolePermission row);
}