package com.lzy.jshow.mapper;

import com.lzy.jshow.entity.SysPermission;
import com.lzy.jshow.entity.SysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    long countByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int deleteByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int insert(SysPermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int insertSelective(SysPermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    List<SysPermission> selectByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    SysPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByExampleSelective(@Param("row") SysPermission row, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByExample(@Param("row") SysPermission row, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByPrimaryKeySelective(SysPermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByPrimaryKey(SysPermission row);
}