package com.lzy.jshow.mapper;

import com.lzy.jshow.entity.SysRolePermission;
import com.lzy.jshow.entity.SysRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    long countByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int deleteByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int insert(SysRolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int insertSelective(SysRolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    List<SysRolePermission> selectByExample(SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    SysRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByExampleSelective(@Param("row") SysRolePermission row, @Param("example") SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByExample(@Param("row") SysRolePermission row, @Param("example") SysRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByPrimaryKeySelective(SysRolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Sat May 24 11:16:48 HKT 2025
     */
    int updateByPrimaryKey(SysRolePermission row);
}