package com.lzy.jshow.mapper;

import com.lzy.jshow.entity.SysRole;
import com.lzy.jshow.entity.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    long countByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int deleteByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int insert(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int insertSelective(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    List<SysRole> selectByExample(SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    SysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByExampleSelective(@Param("row") SysRole row, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByExample(@Param("row") SysRole row, @Param("example") SysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByPrimaryKeySelective(SysRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    int updateByPrimaryKey(SysRole row);
}