package com.lzy.jshow.entity;

import java.io.Serializable;
import java.util.Date;

public class AppUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.username
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.email
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.phone
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.status
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.create_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.update_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.username
     *
     * @return the value of app_user.username
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.username
     *
     * @param username the value for app_user.username
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.email
     *
     * @return the value of app_user.email
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.email
     *
     * @param email the value for app_user.email
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.phone
     *
     * @return the value of app_user.phone
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.phone
     *
     * @param phone the value for app_user.phone
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.status
     *
     * @return the value of app_user.status
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.status
     *
     * @param status the value for app_user.status
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.create_time
     *
     * @return the value of app_user.create_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.create_time
     *
     * @param createTime the value for app_user.create_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.update_time
     *
     * @return the value of app_user.update_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.update_time
     *
     * @param updateTime the value for app_user.update_time
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Sat May 24 11:16:49 HKT 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}