package com.lzy.jshow.entity;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.perm_name
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private String permName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.perm_code
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private String permCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.description
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.perm_type
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private Byte permType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.parent_id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.create_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.update_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.perm_name
     *
     * @return the value of permission.perm_name
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.perm_name
     *
     * @param permName the value for permission.perm_name
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setPermName(String permName) {
        this.permName = permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.perm_code
     *
     * @return the value of permission.perm_code
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public String getPermCode() {
        return permCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.perm_code
     *
     * @param permCode the value for permission.perm_code
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setPermCode(String permCode) {
        this.permCode = permCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.description
     *
     * @return the value of permission.description
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.description
     *
     * @param description the value for permission.description
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.perm_type
     *
     * @return the value of permission.perm_type
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public Byte getPermType() {
        return permType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.perm_type
     *
     * @param permType the value for permission.perm_type
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setPermType(Byte permType) {
        this.permType = permType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.parent_id
     *
     * @return the value of permission.parent_id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.parent_id
     *
     * @param parentId the value for permission.parent_id
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.create_time
     *
     * @return the value of permission.create_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.create_time
     *
     * @param createTime the value for permission.create_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.update_time
     *
     * @return the value of permission.update_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.update_time
     *
     * @param updateTime the value for permission.update_time
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Sat May 24 11:12:43 HKT 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permName=").append(permName);
        sb.append(", permCode=").append(permCode);
        sb.append(", description=").append(description);
        sb.append(", permType=").append(permType);
        sb.append(", parentId=").append(parentId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}